### PR TITLE
Add threads, edit envs

### PR DESCRIPTION
**Pull request by wharvey31**
I had to make some changes to the conda envs and added consistent runtime resources for each rule.

### CODE REVIEW

**Comment by mir-cat** [comment]
Hi! Is there a reason that you added the flag to specify memory per thread (div_mem)? My understanding is that snakemake limits the memory for the whole job, which would make this not necessary?

**Comment by wharvey31** [comment]
Hi Mir,

Sorry for the confusion. Our job scheduler takes in memory requirements on a per thread basis. So the memory requests specified in the rules are multiplied by the number of threads. We might be in the minority regarding our job scheduler behavior, but I saw it as relatively unimpactful to have an optional config argument which helps with this problem. When this is set to false, memory resources are unaffected.

**Comment by mir-cat** [comment]
Just wanted to learn! I agree that the impact of including such a config option is low.

**Comment by mir-cat** [comment]
> Resolved conflict where input rules had a temp designation. I would also recommend using the dot syntax to link together rules which can help snakemake determine DAGs for large pipelines more quickly. e.g. rules.split_haplotype_annotations.output.hap1 vs. 'rukki/{sample}/{sample}_hap1_nodes.txt'

This is an issue that I had already opened as a refactoring goal :P

**Comment by mir-cat** [comment]
I also wanted to ask: Is the consistent resource specification something that is also needed for your cluster job scheduler? Or is it a style choice?

**Pull request closed without merging**
